PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rpath: <https://w3id.org/lodsight/rdf-path#>
PREFIX spin:  <http://spinrdf.org/spin#>

CONSTRUCT {
  [] a spin:ConstraintViolation ;
    spin:violationRoot ?edge ;
    spin:violationPath rpath:start ;
    spin:violationValue ?start ;
    rdfs:label "Only edge ends can be datatypes."@en .
}
WHERE {
  [] rpath:edges/rdf:rest*/rdf:first ?edge .
  ?edge rpath:start ?start .
  ?start a [ a rdfs:Datatype ] .
}
